# Generated by Django 4.2.9 on 2024-04-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customer_dob_customer_fullname_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdish',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
